In [1]:
! pip3 install snscrape

Collecting snscrape
  Downloading snscrape-0.4.3.20220106-py3-none-any.whl (59 kB)
Requirement already satisfied: pytz in c:\users\kelvin\miniconda3\envs\comv\lib\site-packages (from snscrape) (2021.3)
Collecting lxml
  Downloading lxml-4.8.0-cp38-cp38-win_amd64.whl (3.6 MB)
Requirement already satisfied: filelock in c:\users\kelvin\miniconda3\envs\comv\lib\site-packages (from snscrape) (3.6.0)
Requirement already satisfied: beautifulsoup4 in c:\users\kelvin\miniconda3\envs\comv\lib\site-packages (from snscrape) (4.10.0)
Requirement already satisfied: requests[socks] in c:\users\kelvin\miniconda3\envs\comv\lib\site-packages (from snscrape) (2.27.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\kelvin\miniconda3\envs\comv\lib\site-packages (from beautifulsoup4->snscrape) (2.3.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kelvin\miniconda3\envs\comv\lib\site-packages (from requests[socks]->snscrape) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kelvin\miniconda3\envs\comv\lib\site-packages (from requests[socks]->snscrape) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\kelvin\miniconda3\envs\comv\lib\site-packages (from requests[socks]->snscrape) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\kelvin\miniconda3\envs\comv\lib\site-packages (from requests[socks]->snscrape) (1.26.8)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\kelvin\miniconda3\envs\comv\lib\site-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: lxml, snscrape
Successfully installed lxml-4.8.0 snscrape-0.4.3.20220106

In [7]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('sentosa  lang:id since:2022-01-01 until:2022-03-31').get_items()):
    if i>5000:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# sample search string
# sentosa (#sentosa) lang:id since:2022-01-01 until:2022-03-31'

# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

In [8]:
tweets_df2

,Datetime,Tweet Id,Text,Username
0,2022-03-30 23:54:24+00:00,1509318154346176512,wdwdwd semoga lancar jaya sentosa thq tudei,owrieyow
1,2022-03-30 23:36:14+00:00,1509313581833396224,@A100888 Amin om.. Semoga akun nya aman sentosa,roedhy06
2,2022-03-30 23:34:15+00:00,1509313084468326400,"@nctzenbase Terimakasih para Mutualku, TL ku s...",MeKissmiss
3,2022-03-30 23:21:20+00:00,1509309834381783042,PLIS IYA INI PLAYLIST FESTIVAL ASTAGAAAA duit ...,ehmmtasty
4,2022-03-30 23:17:36+00:00,1509308894065344512,smgt ya xiao main semoga sehat sentosa,raidefn
...,...,...,...,...
4996,2022-03-09 10:25:59+00:00,1501504563349975042,@yaamahmud @rougenetizen @Yyantikk @KTY747 @jo...,ayshafly3424
4997,2022-03-09 10:25:37+00:00,1501504474443300866,@andweeo yang gamau brarti masih mentingin kel...,onyageraldine
4998,2022-03-09 10:24:16+00:00,1501504131605090309,Padahal hidup apa adanya itu bikin damai tenan...,dianywidya
4999,2022-03-09 10:21:33+00:00,1501503447694123011,muka gue ramah adem sentosa kokðŸ’€ https://t.co/...,gurlllreen
5000,2022-03-09 10:04:23+00:00,1501499128697659392,Alhamdulillahnya pas sidang aman jaya sentosa ...,Artemize_

In [9]:
removed_tzone=tweets_df2

removed_tzone['Datetime'] = removed_tzone['Datetime'].dt.tz_localize(None)

removed_tzone

,Datetime,Tweet Id,Text,Username
0,2022-03-30 23:54:24,1509318154346176512,wdwdwd semoga lancar jaya sentosa thq tudei,owrieyow
1,2022-03-30 23:36:14,1509313581833396224,@A100888 Amin om.. Semoga akun nya aman sentosa,roedhy06
2,2022-03-30 23:34:15,1509313084468326400,"@nctzenbase Terimakasih para Mutualku, TL ku s...",MeKissmiss
3,2022-03-30 23:21:20,1509309834381783042,PLIS IYA INI PLAYLIST FESTIVAL ASTAGAAAA duit ...,ehmmtasty
4,2022-03-30 23:17:36,1509308894065344512,smgt ya xiao main semoga sehat sentosa,raidefn
...,...,...,...,...
4996,2022-03-09 10:25:59,1501504563349975042,@yaamahmud @rougenetizen @Yyantikk @KTY747 @jo...,ayshafly3424
4997,2022-03-09 10:25:37,1501504474443300866,@andweeo yang gamau brarti masih mentingin kel...,onyageraldine
4998,2022-03-09 10:24:16,1501504131605090309,Padahal hidup apa adanya itu bikin damai tenan...,dianywidya
4999,2022-03-09 10:21:33,1501503447694123011,muka gue ramah adem sentosa kokðŸ’€ https://t.co/...,gurlllreen
5000,2022-03-09 10:04:23,1501499128697659392,Alhamdulillahnya pas sidang aman jaya sentosa ...,Artemize_

In [10]:
removed_tzone.to_excel('tweets.xlsx', sheet_name='sheet1', index=False)